/**
 * Memory map file for Dcm
 *
 * Memory sections according to ASR 4.1.3 definitions of the Memory Mapping
 * specifications. Note that deprecated memory sections are not generated.
 */

/*lint -e451 AUTOSAR API SWS_MemMap_00003 */

#define Dcm_MEMMAP_ERROR

#ifdef Dcm_START_SEC_VAR_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_NO_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_NO_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_NO_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_NO_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_NO_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_NO_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_POWER_ON_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_POWER_ON_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_FAST_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_FAST_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_FAST_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_FAST_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_FAST_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_FAST_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_NO_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_NO_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_FAST_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_NO_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_NO_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_FAST_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_NO_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_NO_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_FAST_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_FAST_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_FAST_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_FAST_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_FAST_POWER_ON_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_NO_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_NO_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_NO_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_NO_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SLOW_POWER_ON_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_INIT_8
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_INIT_8
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_INIT_16
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_INIT_16
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_INIT_32
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_INIT_32
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_8
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_8
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_16
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_16
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_NO_INIT_32
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_NO_INIT_32
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_8
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_16
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_CLEARED_32
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
#endif

#ifdef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
#endif

#ifdef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_NO_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_NO_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_CLEARED_32
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_POWER_ON_INIT_32
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_ZONE_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_ZONE_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_ZONE_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_ZONE_32
#endif

#ifdef Dcm_START_SEC_CONST_SAVED_RECOVERY_ZONE
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_SAVED_RECOVERY_ZONE
#endif

#ifdef Dcm_STOP_SEC_CONST_SAVED_RECOVERY_ZONE
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_SAVED_RECOVERY_ZONE
#endif

#ifdef Dcm_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_BOOLEAN
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_8
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_8
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_16
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_16
#endif

#ifdef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_VAR_SAVED_RECOVERY_ZONE_32
#endif

#ifdef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_VAR_SAVED_RECOVERY_ZONE_32
#endif

#ifdef Dcm_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_CONST_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_CONST_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_BOOLEAN
#endif

#ifdef Dcm_START_SEC_CONST_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_8
#endif

#ifdef Dcm_STOP_SEC_CONST_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_8
#endif

#ifdef Dcm_START_SEC_CONST_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_16
#endif

#ifdef Dcm_STOP_SEC_CONST_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_16
#endif

#ifdef Dcm_START_SEC_CONST_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONST_32
#endif

#ifdef Dcm_STOP_SEC_CONST_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONST_32
#endif

#ifdef Dcm_START_SEC_CALIB_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CALIB_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_CALIB_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CALIB_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_CALIB_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CALIB_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_CALIB_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CALIB_BOOLEAN
#endif

#ifdef Dcm_START_SEC_CALIB_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CALIB_8
#endif

#ifdef Dcm_STOP_SEC_CALIB_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CALIB_8
#endif

#ifdef Dcm_START_SEC_CALIB_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CALIB_16
#endif

#ifdef Dcm_STOP_SEC_CALIB_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CALIB_16
#endif

#ifdef Dcm_START_SEC_CALIB_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CALIB_32
#endif

#ifdef Dcm_STOP_SEC_CALIB_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CALIB_32
#endif

#ifdef Dcm_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONFIG_DATA_UNSPECIFIED
#endif

#ifdef Dcm_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#endif

#ifdef Dcm_START_SEC_CONFIG_DATA_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONFIG_DATA_BOOLEAN
#endif

#ifdef Dcm_STOP_SEC_CONFIG_DATA_BOOLEAN
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONFIG_DATA_BOOLEAN
#endif

#ifdef Dcm_START_SEC_CONFIG_DATA_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONFIG_DATA_8
#endif

#ifdef Dcm_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONFIG_DATA_8
#endif

#ifdef Dcm_START_SEC_CONFIG_DATA_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONFIG_DATA_16
#endif

#ifdef Dcm_STOP_SEC_CONFIG_DATA_16
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONFIG_DATA_16
#endif

#ifdef Dcm_START_SEC_CONFIG_DATA_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CONFIG_DATA_32
#endif

#ifdef Dcm_STOP_SEC_CONFIG_DATA_32
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CONFIG_DATA_32
#endif

#ifdef Dcm_START_SEC_CODE
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CODE
#endif

#ifdef Dcm_STOP_SEC_CODE
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CODE
#endif

#ifdef Dcm_START_SEC_CODE_FAST
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CODE_FAST
#endif

#ifdef Dcm_STOP_SEC_CODE_FAST
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CODE_FAST
#endif

#ifdef Dcm_START_SEC_CODE_SLOW
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_START_SEC_CODE_SLOW
#endif

#ifdef Dcm_STOP_SEC_CODE_SLOW
#include "MemMap.h"
#undef Dcm_MEMMAP_ERROR
#undef Dcm_STOP_SEC_CODE_SLOW
#endif

#ifdef Dcm_MEMMAP_ERROR
#error "Dcm_MemMap.h error, section not mapped"
#endif

