
/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 * 
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with  
 * the terms contained in the written license agreement between you and ArcCore, 
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as 
 * published by the Free Software Foundation and appearing in the file 
 * LICENSE.GPL included in the packaging of this file or here 
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

/* Generator version: 7.0.0
 * AUTOSAR version:   4.3.0
 */

#include "Port.h"




static const ArcPort_InputSelectConfigType PortInputSelectConfigData[] = {
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_3
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_3, /* PCR	3	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_7
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_7, /* PCR	7	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_8
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_8, /* PCR	8	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_9
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_9, /* PCR	9	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_10
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_10, /* PCR	10	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_11
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_11, /* PCR	11	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_OTHER2_PAD_12
	INPUT_SELECT_PORT_PIN_MODE_OTHER2_PAD_12, /* PCR	12	: PORT_PIN_MODE_OTHER2 */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_17
	INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_17, /* PCR	17	: PORT_PIN_MODE_CAN */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_76
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_76, /* PCR	76	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_77
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_77, /* PCR	77	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_95
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_95, /* PCR	95	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_100
	INPUT_SELECT_PORT_PIN_MODE_PWM_PAD_100, /* PCR	100	: PORT_PIN_MODE_PWM */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_142
	INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_142, /* PCR	142	: PORT_PIN_MODE_SPI */
#endif
	{PORT_INVALID_REG, 0u} /* end marker */
};

/*lint -save -e835 -e9027 -e845 FALSE POSITIVE Zero given as right argument to | is okay (Generated code and depending on the defines this is true for some defines) */ 
static const ArcPort_PadConfigType PortPadConfigData[] = {
	{3, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(3, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	3	: PORT_PIN_MODE_ETH */
	{7, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(7, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	7	: PORT_PIN_MODE_ETH */
	{8, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(8, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	8	: PORT_PIN_MODE_ETH */
	{9, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(9, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	9	: PORT_PIN_MODE_ETH */
	{10, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(10, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	10	: PORT_PIN_MODE_ETH */
	{11, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(11, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	11	: PORT_PIN_MODE_ETH */
	{12, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(12, PORT_PIN_MODE_OTHER2, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	12	: PORT_PIN_MODE_OTHER2 */
	{13, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(13, PORT_PIN_MODE_SPI, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	13	: PORT_PIN_MODE_SPI */
	{14, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(14, PORT_PIN_MODE_SPI, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_UP  | PORT_OUTPUT )}, /* PCR	14	: PORT_PIN_MODE_SPI */
	{15, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(15, PORT_PIN_MODE_SPI, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_UP  | PORT_OUTPUT )}, /* PCR	15	: PORT_PIN_MODE_SPI */
	{16, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(16, PORT_PIN_MODE_CAN, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	16	: PORT_PIN_MODE_CAN */
	{17, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(17, PORT_PIN_MODE_CAN, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_NONE  )}, /* PCR	17	: PORT_PIN_MODE_CAN */
	{26, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(26, PORT_PIN_MODE_ADC, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	26	: PORT_PIN_MODE_ADC */
	{61, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(61, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	61	: PORT_PIN_MODE_ETH */
	{76, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(76, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	76	: PORT_PIN_MODE_ETH */
	{77, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(77, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	77	: PORT_PIN_MODE_ETH */
	{87, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(87, PORT_PIN_MODE_SPI, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_DOWN  | PORT_OUTPUT )}, /* PCR	87	: PORT_PIN_MODE_SPI */
	{94, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(94, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	94	: PORT_PIN_MODE_ETH */
	{95, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(95, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	95	: PORT_PIN_MODE_ETH */
	{96, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(96, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	96	: PORT_PIN_MODE_ETH */
	{97, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(97, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	97	: PORT_PIN_MODE_ETH */
	{98, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(98, PORT_PIN_MODE_DIO, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_DOWN  | PORT_OUTPUT )}, /* PCR	98	: PORT_PIN_MODE_DIO */
	{99, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(99, PORT_PIN_MODE_DIO, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_DOWN  | PORT_OUTPUT )}, /* PCR	99	: PORT_PIN_MODE_DIO */
	{100, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(100, PORT_PIN_MODE_PWM, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	100	: PORT_PIN_MODE_PWM */
	{101, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(101, PORT_PIN_MODE_PWM, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	101	: PORT_PIN_MODE_PWM */
	{108, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(108, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	108	: PORT_PIN_MODE_ETH */
	{109, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(109, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	109	: PORT_PIN_MODE_ETH */
	{112, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(112, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	112	: PORT_PIN_MODE_ETH */
	{113, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(113, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	113	: PORT_PIN_MODE_ETH */
	{114, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(114, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	114	: PORT_PIN_MODE_ETH */
	{115, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(115, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	115	: PORT_PIN_MODE_ETH */
	{139, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(139, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	139	: PORT_PIN_MODE_ETH */
	{142, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(142, PORT_PIN_MODE_SPI, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	142	: PORT_PIN_MODE_SPI */
	{143, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(143, PORT_PIN_MODE_SPI, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_UP  | PORT_OUTPUT )}, /* PCR	143	: PORT_PIN_MODE_SPI */
	{144, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(144, PORT_PIN_MODE_DIO, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_UP  | PORT_OUTPUT )}, /* PCR	144	: PORT_PIN_MODE_DIO */
	{145, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(145, PORT_PIN_MODE_SPI, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	145	: PORT_PIN_MODE_SPI */
	{195, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(195, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	195	: PORT_PIN_MODE_ETH */
	{PORT_INVALID_REG, STD_OFF, STD_OFF, 0u} /* end marker */
};
/*lint -restore */


static const ArcPort_OutConfigType PortOutConfigData[] = {
	{98u, PORT_GPDO_HIGH}, /* GPDO	98 */
	{99u, PORT_GPDO_RESET}, /* GPDO	99 */
	{144u, PORT_GPDO_RESET}, /* GPDO	144 */
	{PORT_INVALID_REG, 0u} /* end marker */
};



const Port_ConfigType PortConfigData =
{
  .padConfig = PortPadConfigData,
  .outConfig = PortOutConfigData,
  .inputSelectConfig = PortInputSelectConfigData
};


