$(PROJECT_NAME)_$(MCU_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Mcu_Cfg.h
$(PROJECT_NAME)_$(MCU_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Mcu_PBfg.c
$(PROJECT_NAME)_$(MCU_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Mcu_LCfg.c
$(PROJECT_NAME)_$(MCU_MODULE_NAME)_CONFIG_FILES += $(CFG_OUTPUT_DIR)/Mcu.mk

$(PROJECT_NAME)_CONFIG_FILES += $($(PROJECT_NAME)_$(MCU_MODULE_NAME)_CONFIG_FILES)

inc-$(USE_MCU) +=   $($(PROJECT_NAME)_CONFIG_FILES)
inc-$(USE_MCU) +=   $($(PROJECT_NAME)_CONFIG_FILES)
vpath-$(USE_MCU) += $($(PROJECT_NAME)_CONFIG_FILES)