/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

#ifndef _MPC5777CPORTDEFS_H
#define _MPC5777CPORTDEFS_H

/* Pad: 113 */
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_113_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 114 */
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_114_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 115 */
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_115_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 116 */
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_116_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 117 */
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER2 PORT_FUNC3 
#define PIN_FUNCTION_REG_117_PORT_PIN_MODE_OTHER3 PORT_FUNC4 

/* Pad: 118 */
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_118_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 119 */
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_119_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 120 */
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_120_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 121 */
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_121_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 122 */
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_122_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 123 */
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_123_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 124 */
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER2 PORT_FUNC3 
#define PIN_FUNCTION_REG_124_PORT_PIN_MODE_OTHER3 PORT_FUNC4 

/* Pad: 125 */
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER1 PORT_FUNC2 
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER2 PORT_FUNC3 
#define PIN_FUNCTION_REG_125_PORT_PIN_MODE_OTHER3 PORT_FUNC4 

/* Pad: 126 */
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_126_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 127 */
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_127_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 128 */
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_128_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 129 */
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_129_PORT_PIN_MODE_CAN PORT_FUNC3

/* Pad: 130 */
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_130_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 131 */
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_131_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 132 */
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_132_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 133 */
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_133_PORT_PIN_MODE_CAN PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_133 {1, 0}

/* Pad: 134 */
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_134_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 135 */
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_135_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 136 */
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_136_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 137 */
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_137_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 138 */
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_138 {7, 0}
#define PIN_FUNCTION_REG_138_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 139 */
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_139 {7, 0}
#define PIN_FUNCTION_REG_139_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 140 */
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_140 {7, 0}
#define PIN_FUNCTION_REG_140_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 141 */
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_141 {7, 0}
#define PIN_FUNCTION_REG_141_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 142 */
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_142 {7, 0}
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_142_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 143 */
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_143 {7, 0}
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_143_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 144 */
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_144 {7, 0}
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_144_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 145 */
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_145 {7, 0}
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_145_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 146 */
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_146_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 147 */
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_147_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 148 */
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_148_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 149 */
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_149_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 150 */
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_150_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 151 */
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_151_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 152 */
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_152_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 153 */
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_153_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 154 */
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_154_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 155 */
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_155_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 156 */
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_156_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 157 */
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_157_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 158 */
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_158_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 159 */
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_159_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 160 */
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_160_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 161 */
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_161_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 162 */
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_162_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 163 */
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_163_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 164 */
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_164_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 165 */
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_165_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 166 */
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_166_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 167 */
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_167_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 168 */
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_168_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 169 */
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_169_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 170 */
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_170_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 171 */
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_171_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 172 */
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_172_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 173 */
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_173_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 174 */
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_174_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 175 */
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_175_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 176 */
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_176_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 177 */
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_177_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 178 */
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_178_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 440 */
#define PIN_FUNCTION_REG_440_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_440_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 441 */
#define PIN_FUNCTION_REG_441_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_441 {10, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_441 {0, 0} 

/* Pad: 442 */
#define PIN_FUNCTION_REG_442_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_442 {10, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_442 {0, 0} 

/* Pad: 443 */
#define PIN_FUNCTION_REG_443_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_443_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_443 {0, 0} 

/* Pad: 444 */
#define PIN_FUNCTION_REG_444_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_444 {10, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_444 {0, 0} 

/* Pad: 445 */
#define PIN_FUNCTION_REG_445_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_445_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_445 {0, 0} 
#define PIN_FUNCTION_REG_445_PORT_PIN_MODE_OTHER2 PORT_FUNC3 

/* Pad: 446 */
#define PIN_FUNCTION_REG_446_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_446_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_446_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_446 {0, 0} 

/* Pad: 447 */
#define PIN_FUNCTION_REG_447_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_447_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_447_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_447 {0, 0} 

/* Pad: 448 */
#define PIN_FUNCTION_REG_448_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_448_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_448_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_448 {0, 0} 

/* Pad: 449 */
#define PIN_FUNCTION_REG_449_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_449 {10, 0}
#define PIN_FUNCTION_REG_449_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_449 {0, 0} 

/* Pad: 450 */
#define PIN_FUNCTION_REG_450_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_450 {10, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_450 {0, 0} 

/* Pad: 451 */
#define PIN_FUNCTION_REG_451_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_451 {10, 0}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_451 {0, 0} 

/* Pad: 452 */
#define PIN_FUNCTION_REG_452_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_452 {10, 0}

/* Pad: 453 */
#define PIN_FUNCTION_REG_453_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_453 {10, 0}
#define PIN_FUNCTION_REG_453_PORT_PIN_MODE_CAN PORT_FUNC3

/* Pad: 454 */
#define PIN_FUNCTION_REG_454_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_454 {10, 0}
#define PIN_FUNCTION_REG_454_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_454_PORT_PIN_MODE_OTHER2 PORT_FUNC4 

/* Pad: 455 */
#define PIN_FUNCTION_REG_455_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_455 {10, 0}
#define PIN_FUNCTION_REG_455_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_455_PORT_PIN_MODE_OTHER2 PORT_FUNC4 

/* Pad: 456 */
#define PIN_FUNCTION_REG_456_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_456 {10, 0}
#define PIN_FUNCTION_REG_456_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_456 {1, 0}
#define PIN_FUNCTION_REG_456_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 457 */
#define PIN_FUNCTION_REG_457_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_457_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_457_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_457_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 458 */
#define PIN_FUNCTION_REG_458_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_458_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_458_PORT_PIN_MODE_LIN PORT_FUNC2 
#define PIN_FUNCTION_REG_458_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 459 */
#define PIN_FUNCTION_REG_459_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_459_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_459_PORT_PIN_MODE_LIN PORT_FUNC2 

/* Pad: 460 */
#define PIN_FUNCTION_REG_460_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_460_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_460_PORT_PIN_MODE_LIN PORT_FUNC2 
#define PIN_FUNCTION_REG_460_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 461 */
#define PIN_FUNCTION_REG_461_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_461_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_461_PORT_PIN_MODE_LIN PORT_FUNC2 
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_461 {4, 8}
#define PIN_FUNCTION_REG_461_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 462 */
#define PIN_FUNCTION_REG_462_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_462_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_462_PORT_PIN_MODE_LIN PORT_FUNC2 

/* Pad: 463 */
#define PIN_FUNCTION_REG_463_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_463_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_463_PORT_PIN_MODE_LIN PORT_FUNC2 
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_463 {4, 16}

/* Pad: 464 */
#define PIN_FUNCTION_REG_464_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_464_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_464_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 465 */
#define PIN_FUNCTION_REG_465_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_465_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_465_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 466 */
#define PIN_FUNCTION_REG_466_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_466_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_466_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 467 */
#define PIN_FUNCTION_REG_467_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_467_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_467_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 468 */
#define PIN_FUNCTION_REG_468_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_468_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_468_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_468_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 469 */
#define PIN_FUNCTION_REG_469_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_469_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_469_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_469 {2, 4194304}
#define PIN_FUNCTION_REG_469_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 470 */
#define PIN_FUNCTION_REG_470_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_470_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_470_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_470 {2, 262144}
#define PIN_FUNCTION_REG_470_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 471 */
#define PIN_FUNCTION_REG_471_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_471_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_471_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_471_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 472 */
#define PIN_FUNCTION_REG_472_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_472_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_472_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_472 {2, 1048576}
#define PIN_FUNCTION_REG_472_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 179 */
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_179_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 180 */
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_180_PORT_PIN_MODE_SPI PORT_FUNC4

/* Pad: 181 */
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_181_PORT_PIN_MODE_SPI PORT_FUNC4

/* Pad: 182 */
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_182_PORT_PIN_MODE_SPI PORT_FUNC4

/* Pad: 183 */
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_183_PORT_PIN_MODE_SPI PORT_FUNC4

/* Pad: 184 */
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_184_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 185 */
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_185_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 186 */
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_186_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 187 */
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_187_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 188 */
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_188_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 189 */
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_189_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_189 {2, 524288}

/* Pad: 190 */
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_190_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_190 {2, 2097152}

/* Pad: 191 */
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_191_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 192 */
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_192_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 193 */
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_CAN PORT_FUNC3
#define PIN_FUNCTION_REG_193_PORT_PIN_MODE_OTHER0 PORT_FUNC4

/* Pad: 194 */
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_PWM PORT_FUNC1
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_CAN PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_194 {1, 1024}
#define PIN_FUNCTION_REG_194_PORT_PIN_MODE_OTHER0 PORT_FUNC4

/* Pad: 195 */
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_CAN PORT_FUNC3
#define PIN_FUNCTION_REG_195_PORT_PIN_MODE_OTHER1 PORT_FUNC4 

/* Pad: 196 */
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_CAN PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_196 {1, 8}
#define PIN_FUNCTION_REG_196_PORT_PIN_MODE_OTHER1 PORT_FUNC4 

/* Pad: 197 */
#define PIN_FUNCTION_REG_197_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_197_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_197_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_197_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 198 */
#define PIN_FUNCTION_REG_198_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_198_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_198_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_198_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 199 */
#define PIN_FUNCTION_REG_199_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_199_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_199_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_199_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 200 */
#define PIN_FUNCTION_REG_200_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_200_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_200_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_200_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 201 */
#define PIN_FUNCTION_REG_201_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_201_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_201_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_201_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 202 */
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_OTHER0 PORT_FUNC2 
#define PIN_FUNCTION_REG_202_PORT_PIN_MODE_OTHER1 PORT_FUNC3 

/* Pad: 203 */
#define PIN_FUNCTION_REG_203_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_203_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_203_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_203 {2, 1024}

/* Pad: 204 */
#define PIN_FUNCTION_REG_204_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_204_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_204_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 432 */
#define PIN_FUNCTION_REG_432_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_432_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_432_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 433 */
#define PIN_FUNCTION_REG_433_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_433_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_433_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 434 */
#define PIN_FUNCTION_REG_434_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_434_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_434_PORT_PIN_MODE_SPI PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_434 {2, 131072}

/* Pad: 435 */
#define PIN_FUNCTION_REG_435_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_435_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_435_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 436 */
#define PIN_FUNCTION_REG_436_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_436_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_436_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 437 */
#define PIN_FUNCTION_REG_437_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_437_PORT_PIN_MODE_PWM PORT_FUNC1 
#define PIN_FUNCTION_REG_437_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 476 */
#define PIN_FUNCTION_REG_476_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_476 {7, 1073741824}
#define PIN_FUNCTION_REG_476_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 477 */
#define PIN_FUNCTION_REG_477_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_477 {7, 268435456}
#define PIN_FUNCTION_REG_477_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 478 */
#define PIN_FUNCTION_REG_478_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_478 {7, 67108864}
#define PIN_FUNCTION_REG_478_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 479 */
#define PIN_FUNCTION_REG_479_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_479 {7, 16777216}
#define PIN_FUNCTION_REG_479_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 480 */
#define PIN_FUNCTION_REG_480_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_480 {7, 4194304}
#define PIN_FUNCTION_REG_480_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 481 */
#define PIN_FUNCTION_REG_481_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_481 {7, 1048576}
#define PIN_FUNCTION_REG_481_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 482 */
#define PIN_FUNCTION_REG_482_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_482 {7, 262144}
#define PIN_FUNCTION_REG_482_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 483 */
#define PIN_FUNCTION_REG_483_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_483 {7, 65536}
#define PIN_FUNCTION_REG_483_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 484 */
#define PIN_FUNCTION_REG_484_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_484 {10, 1073741824}
#define PIN_FUNCTION_REG_484_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 485 */
#define PIN_FUNCTION_REG_485_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_485 {10, 268435456}
#define PIN_FUNCTION_REG_485_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 486 */
#define PIN_FUNCTION_REG_486_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_486 {10, 67108864}
#define PIN_FUNCTION_REG_486_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 487 */
#define PIN_FUNCTION_REG_487_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_487 {10, 16777216}
#define PIN_FUNCTION_REG_487_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 488 */
#define PIN_FUNCTION_REG_488_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_488 {10, 4194304}
#define PIN_FUNCTION_REG_488_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 489 */
#define PIN_FUNCTION_REG_489_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_489 {10, 1048576}
#define PIN_FUNCTION_REG_489_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 490 */
#define PIN_FUNCTION_REG_490_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_490 {10, 262144}
#define PIN_FUNCTION_REG_490_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 491 */
#define PIN_FUNCTION_REG_491_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_491 {10, 65536}
#define PIN_FUNCTION_REG_491_PORT_PIN_MODE_PWM PORT_FUNC3 

/* Pad: 475 */
#define PIN_FUNCTION_REG_475_PORT_PIN_MODE_DIO PORT_FUNC0
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_475 {0, 0}

/* Pad: 474 */
#define PIN_FUNCTION_REG_474_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_474_PORT_PIN_MODE_ETH PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_474 {0, 4096}

/* Pad: 248 */
#define PIN_FUNCTION_REG_248_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_248_PORT_PIN_MODE_ETH PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_248 {0, 1}

/* Pad: 249 */
#define PIN_FUNCTION_REG_249_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_249_PORT_PIN_MODE_ETH PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_249 {0, 4}

/* Pad: 250 */
#define PIN_FUNCTION_REG_250_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_250_PORT_PIN_MODE_ETH PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_250 {0, 16}

/* Pad: 251 */
#define PIN_FUNCTION_REG_251_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_251_PORT_PIN_MODE_ETH PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_251 {0, 64}

/* Pad: 252 */
#define PIN_FUNCTION_REG_252_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_252_PORT_PIN_MODE_ETH PORT_FUNC1
#define PIN_FUNCTION_REG_252_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 253 */
#define PIN_FUNCTION_REG_253_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_253_PORT_PIN_MODE_ETH PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_253 {0, 1024}

/* Pad: 83 */
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_LIN PORT_FUNC2 
#define PIN_FUNCTION_REG_83_PORT_PIN_MODE_OTHER0 PORT_FUNC3 

/* Pad: 84 */
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_LIN PORT_FUNC2 
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_84 {4, 4}
#define PIN_FUNCTION_REG_84_PORT_PIN_MODE_OTHER0 PORT_FUNC3 
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_84 {1, 1} 

/* Pad: 85 */
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_85_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 86 */
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_86_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 87 */
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_87_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 88 */
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_88_PORT_PIN_MODE_LIN PORT_FUNC3 

/* Pad: 246 */
#define PIN_FUNCTION_REG_246_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_246_PORT_PIN_MODE_CAN PORT_FUNC1
#define PIN_FUNCTION_REG_246_PORT_PIN_MODE_OTHER0 PORT_FUNC3

/* Pad: 247 */
#define PIN_FUNCTION_REG_247_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_247_PORT_PIN_MODE_CAN PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_247 {1, 0}
#define PIN_FUNCTION_REG_247_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_247 {1, 4}

/* Pad: 89 */
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_89_PORT_PIN_MODE_LIN PORT_FUNC1 

/* Pad: 90 */
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_90_PORT_PIN_MODE_LIN PORT_FUNC1 
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_90 {4, 0}

/* Pad: 91 */
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_LIN PORT_FUNC1 
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_SPI PORT_FUNC2
#define PIN_FUNCTION_REG_91_PORT_PIN_MODE_CAN PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_91 {1, 2}

/* Pad: 92 */
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_LIN PORT_FUNC1 
#define INPUT_SELECT_PORT_PIN_MODE_LIN_PAD_92 {4, 0}
#define PIN_FUNCTION_REG_92_PORT_PIN_MODE_SPI PORT_FUNC2

/* Pad: 244 */
#define PIN_FUNCTION_REG_244_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_244_PORT_PIN_MODE_LIN PORT_FUNC1 

/* Pad: 245 */
#define PIN_FUNCTION_REG_245_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_245_PORT_PIN_MODE_LIN PORT_FUNC1 

/* Pad: 93 */
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_93_PORT_PIN_MODE_CAN PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_93 {0, 16384} 

/* Pad: 94 */
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_94_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 95 */
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_95_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 96 */
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_96_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 97 */
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_97_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 98 */
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_ETH PORT_FUNC3
#define PIN_FUNCTION_REG_98_PORT_PIN_MODE_OTHER1 PORT_FUNC4

/* Pad: 99 */
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_ETH PORT_FUNC3
#define PIN_FUNCTION_REG_99_PORT_PIN_MODE_LIN PORT_FUNC4 

/* Pad: 100 */
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_LIN PORT_FUNC3 
#define PIN_FUNCTION_REG_100_PORT_PIN_MODE_ETH PORT_FUNC4

/* Pad: 101 */
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_LIN PORT_FUNC3 
#define PIN_FUNCTION_REG_101_PORT_PIN_MODE_ETH PORT_FUNC4

/* Pad: 102 */
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_102_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 103 */
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_103_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 104 */
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_104_PORT_PIN_MODE_SPI PORT_FUNC1

/* Pad: 105 */
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_105 {2, 0}
#define PIN_FUNCTION_REG_105_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 106 */
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_106_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_106 {2, 0}

/* Pad: 107 */
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_107 {0, 65536} 
#define PIN_FUNCTION_REG_107_PORT_PIN_MODE_ETH PORT_FUNC4

/* Pad: 108 */
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_108_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_108 {2, 16384}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_108 {0, 262144} 

/* Pad: 109 */
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_109 {2, 4096}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_109 {0, 1048576} 
#define PIN_FUNCTION_REG_109_PORT_PIN_MODE_ETH PORT_FUNC4

/* Pad: 110 */
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_110 {2, 65536}
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_110 {0, 4194304} 
#define PIN_FUNCTION_REG_110_PORT_PIN_MODE_ETH PORT_FUNC4

/* Pad: 235 */
#define PIN_FUNCTION_REG_235_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_235_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_235 {2, 0}
#define PIN_FUNCTION_REG_235_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 236 */
#define PIN_FUNCTION_REG_236_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_236_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_236 {2, 0}
#define PIN_FUNCTION_REG_236_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 237 */
#define PIN_FUNCTION_REG_237_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_237_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_237_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 238 */
#define PIN_FUNCTION_REG_238_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_238_PORT_PIN_MODE_SPI PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_SPI_PAD_238 {2, 0}
#define PIN_FUNCTION_REG_238_PORT_PIN_MODE_OTHER0 PORT_FUNC2

/* Pad: 239 */
#define PIN_FUNCTION_REG_239_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_239_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_239_PORT_PIN_MODE_LIN PORT_FUNC2 

/* Pad: 240 */
#define PIN_FUNCTION_REG_240_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_240_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_240_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_240_PORT_PIN_MODE_OTHER1 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_240 {2, 0}

/* Pad: 241 */
#define PIN_FUNCTION_REG_241_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_241_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_241_PORT_PIN_MODE_OTHER0 PORT_FUNC2
#define PIN_FUNCTION_REG_241_PORT_PIN_MODE_OTHER1 PORT_FUNC3
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_241 {2, 0}

/* Pad: 242 */
#define PIN_FUNCTION_REG_242_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_242_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_242_PORT_PIN_MODE_CAN PORT_FUNC2
#define PIN_FUNCTION_REG_242_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_242_PORT_PIN_MODE_OTHER1 PORT_FUNC4

/* Pad: 243 */
#define PIN_FUNCTION_REG_243_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_243_PORT_PIN_MODE_SPI PORT_FUNC1
#define PIN_FUNCTION_REG_243_PORT_PIN_MODE_CAN PORT_FUNC2
#define INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_243 {1, 3}
#define PIN_FUNCTION_REG_243_PORT_PIN_MODE_OTHER0 PORT_FUNC3
#define PIN_FUNCTION_REG_243_PORT_PIN_MODE_OTHER1 PORT_FUNC4
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_243 {2, 8388608}

/* Pad: 256 */
#define PIN_FUNCTION_REG_256_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_256_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 257 */
#define PIN_FUNCTION_REG_257_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_257_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_257_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 258 */
#define PIN_FUNCTION_REG_258_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_258_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_258_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 259 */
#define PIN_FUNCTION_REG_259_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_259_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 260 */
#define PIN_FUNCTION_REG_260_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_260_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 261 */
#define PIN_FUNCTION_REG_261_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_261_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 262 */
#define PIN_FUNCTION_REG_262_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_262_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 263 */
#define PIN_FUNCTION_REG_263_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_263_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_263_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 264 */
#define PIN_FUNCTION_REG_264_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_264_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_264_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 265 */
#define PIN_FUNCTION_REG_265_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_265_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_265_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 266 */
#define PIN_FUNCTION_REG_266_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_266_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_266_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 267 */
#define PIN_FUNCTION_REG_267_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_267_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_267_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 268 */
#define PIN_FUNCTION_REG_268_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_268_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_268_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 269 */
#define PIN_FUNCTION_REG_269_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_269_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_269_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 270 */
#define PIN_FUNCTION_REG_270_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_270_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_270_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 271 */
#define PIN_FUNCTION_REG_271_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_271_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_271_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 272 */
#define PIN_FUNCTION_REG_272_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_272_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_272_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 273 */
#define PIN_FUNCTION_REG_273_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_273_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_273_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 274 */
#define PIN_FUNCTION_REG_274_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_274_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_274_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 275 */
#define PIN_FUNCTION_REG_275_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_275_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_275_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 276 */
#define PIN_FUNCTION_REG_276_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_276_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_276_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 277 */
#define PIN_FUNCTION_REG_277_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_277_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_277_PORT_PIN_MODE_OTHER1 PORT_FUNC2 

/* Pad: 278 */
#define PIN_FUNCTION_REG_278_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_278_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 279 */
#define PIN_FUNCTION_REG_279_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_279_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 280 */
#define PIN_FUNCTION_REG_280_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_280_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 281 */
#define PIN_FUNCTION_REG_281_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_281_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 282 */
#define PIN_FUNCTION_REG_282_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_282_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 283 */
#define PIN_FUNCTION_REG_283_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_283_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 284 */
#define PIN_FUNCTION_REG_284_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_284_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 285 */
#define PIN_FUNCTION_REG_285_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_285_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 286 */
#define PIN_FUNCTION_REG_286_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_286_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 287 */
#define PIN_FUNCTION_REG_287_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_287_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 288 */
#define PIN_FUNCTION_REG_288_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_288_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 289 */
#define PIN_FUNCTION_REG_289_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_289_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 290 */
#define PIN_FUNCTION_REG_290_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_290_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 291 */
#define PIN_FUNCTION_REG_291_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_291_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 292 */
#define PIN_FUNCTION_REG_292_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_292_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 293 */
#define PIN_FUNCTION_REG_293_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_293_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 294 */
#define PIN_FUNCTION_REG_294_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_294_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 295 */
#define PIN_FUNCTION_REG_295_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_295_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 296 */
#define PIN_FUNCTION_REG_296_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_296_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 297 */
#define PIN_FUNCTION_REG_297_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_297_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 298 */
#define PIN_FUNCTION_REG_298_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_298_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 299 */
#define PIN_FUNCTION_REG_299_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_299_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 300 */
#define PIN_FUNCTION_REG_300_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_300_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 301 */
#define PIN_FUNCTION_REG_301_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_301_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 302 */
#define PIN_FUNCTION_REG_302_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_302_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 303 */
#define PIN_FUNCTION_REG_303_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_303_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 304 */
#define PIN_FUNCTION_REG_304_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_304_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 305 */
#define PIN_FUNCTION_REG_305_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_305_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 306 */
#define PIN_FUNCTION_REG_306_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_306_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 307 */
#define PIN_FUNCTION_REG_307_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_307_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 211 */
#define PIN_FUNCTION_REG_211_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_211_PORT_PIN_MODE_OTHER0 PORT_FUNC1

/* Pad: 212 */
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_212 {10, 1} 
#define PIN_FUNCTION_REG_212_PORT_PIN_MODE_OTHER2 PORT_FUNC4 

/* Pad: 213 */
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_213 {10, 4} 
#define PIN_FUNCTION_REG_213_PORT_PIN_MODE_OTHER2 PORT_FUNC4 

/* Pad: 208 */
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_OTHER1 PORT_FUNC3 
#define PIN_FUNCTION_REG_208_PORT_PIN_MODE_OTHER2 PORT_FUNC4 

/* Pad: 209 */
#define PIN_FUNCTION_REG_209_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_209_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define PIN_FUNCTION_REG_209_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_209_PORT_PIN_MODE_OTHER1 PORT_FUNC4 

/* Pad: 210 */
#define PIN_FUNCTION_REG_210_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_210_PORT_PIN_MODE_OTHER0 PORT_FUNC1
#define INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_210 {10, 64} 
#define PIN_FUNCTION_REG_210_PORT_PIN_MODE_SPI PORT_FUNC3
#define PIN_FUNCTION_REG_210_PORT_PIN_MODE_OTHER2 PORT_FUNC4 

/* Pad: 220 */
#define PIN_FUNCTION_REG_220_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 221 */
#define PIN_FUNCTION_REG_221_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 222 */
#define PIN_FUNCTION_REG_222_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 223 */
#define PIN_FUNCTION_REG_223_PORT_PIN_MODE_DIO PORT_FUNC0
#define PIN_FUNCTION_REG_223_PORT_PIN_MODE_LIN PORT_FUNC2 

/* Pad: 75 */
#define PIN_FUNCTION_REG_75_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 76 */
#define PIN_FUNCTION_REG_76_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 77 */
#define PIN_FUNCTION_REG_77_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 78 */
#define PIN_FUNCTION_REG_78_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 79 */
#define PIN_FUNCTION_REG_79_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 80 */
#define PIN_FUNCTION_REG_80_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 81 */
#define PIN_FUNCTION_REG_81_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 82 */
#define PIN_FUNCTION_REG_82_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 231 */
#define PIN_FUNCTION_REG_231_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 232 */
#define PIN_FUNCTION_REG_232_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 233 */
#define PIN_FUNCTION_REG_233_PORT_PIN_MODE_DIO PORT_FUNC0

/* Pad: 234 */
#define PIN_FUNCTION_REG_234_PORT_PIN_MODE_DIO PORT_FUNC0


#endif  /* _MPC5777CPORTDEFS_H*/
