
/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 * 
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with  
 * the terms contained in the written license agreement between you and ArcCore, 
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as 
 * published by the Free Software Foundation and appearing in the file 
 * LICENSE.GPL included in the packaging of this file or here 
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/

/* Generator version: 7.0.0
 * AUTOSAR version:   4.3.0
 */

#include "Port.h"




static const ArcPort_InputSelectConfigType PortInputSelectConfigData[] = {
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_3
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_3, /* PCR	3	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_7
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_7, /* PCR	7	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_8
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_8, /* PCR	8	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_9
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_9, /* PCR	9	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_10
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_10, /* PCR	10	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_11
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_11, /* PCR	11	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_15
	INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_15, /* PCR	15	: PORT_PIN_MODE_CAN */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_35
	INPUT_SELECT_PORT_PIN_MODE_CAN_PAD_35, /* PCR	35	: PORT_PIN_MODE_CAN */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_76
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_76, /* PCR	76	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_77
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_77, /* PCR	77	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_94
	INPUT_SELECT_PORT_PIN_MODE_OTHER1_PAD_94, /* PCR	94	: PORT_PIN_MODE_OTHER1 */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_95
	INPUT_SELECT_PORT_PIN_MODE_ETH_PAD_95, /* PCR	95	: PORT_PIN_MODE_ETH */
#endif
#ifdef INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_97
	INPUT_SELECT_PORT_PIN_MODE_OTHER0_PAD_97, /* PCR	97	: PORT_PIN_MODE_OTHER0 */
#endif
	{PORT_INVALID_REG, 0u} /* end marker */
};

/*lint -save -e835 -e9027 -e845 FALSE POSITIVE Zero given as right argument to | is okay (Generated code and depending on the defines this is true for some defines) */ 
static const ArcPort_PadConfigType PortPadConfigData[] = {
	{0, STD_ON, STD_ON, (PIN_FUNCTION_REG(0, PORT_PIN_MODE_DIO, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MIN | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	0	: PORT_PIN_MODE_DIO */
	{1, STD_ON, STD_ON, (PIN_FUNCTION_REG(1, PORT_PIN_MODE_DIO, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MIN | PORT_PULL_NONE  )}, /* PCR	1	: PORT_PIN_MODE_DIO */
	{3, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(3, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	3	: PORT_PIN_MODE_ETH */
	{7, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(7, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	7	: PORT_PIN_MODE_ETH */
	{8, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(8, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	8	: PORT_PIN_MODE_ETH */
	{9, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(9, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	9	: PORT_PIN_MODE_ETH */
	{10, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(10, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	10	: PORT_PIN_MODE_ETH */
	{11, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(11, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	11	: PORT_PIN_MODE_ETH */
	{13, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(13, PORT_PIN_MODE_CAN, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	13	: PORT_PIN_MODE_CAN */
	{15, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(15, PORT_PIN_MODE_CAN, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_NONE  )}, /* PCR	15	: PORT_PIN_MODE_CAN */
	{35, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(35, PORT_PIN_MODE_CAN, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_NONE  )}, /* PCR	35	: PORT_PIN_MODE_CAN */
	{42, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(42, PORT_PIN_MODE_CAN, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MED | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	42	: PORT_PIN_MODE_CAN */
	{76, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(76, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	76	: PORT_PIN_MODE_ETH */
	{77, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(77, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	77	: PORT_PIN_MODE_ETH */
	{94, STD_ON, STD_OFF, (PIN_FUNCTION_REG(94, PORT_PIN_MODE_OTHER1, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	94	: PORT_PIN_MODE_OTHER1 */
	{94, STD_ON, STD_OFF, (PIN_FUNCTION_REG(94, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	94	: PORT_PIN_MODE_ETH */
	{95, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(95, PORT_PIN_MODE_ETH, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	95	: PORT_PIN_MODE_ETH */
	{96, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(96, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	96	: PORT_PIN_MODE_ETH */
	{97, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(97, PORT_PIN_MODE_OTHER0, 0) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  )}, /* PCR	97	: PORT_PIN_MODE_OTHER0 */
	{98, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(98, PORT_PIN_MODE_DIO, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MIN | PORT_PULL_DOWN  | PORT_OUTPUT )}, /* PCR	98	: PORT_PIN_MODE_DIO */
	{99, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(99, PORT_PIN_MODE_DIO, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MIN | PORT_PULL_DOWN  | PORT_OUTPUT )}, /* PCR	99	: PORT_PIN_MODE_DIO */
	{108, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(108, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	108	: PORT_PIN_MODE_ETH */
	{109, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(109, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	109	: PORT_PIN_MODE_ETH */
	{112, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(112, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	112	: PORT_PIN_MODE_ETH */
	{113, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(113, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	113	: PORT_PIN_MODE_ETH */
	{114, STD_OFF, STD_OFF, (PIN_FUNCTION_REG(114, PORT_PIN_MODE_ETH, 1) | PORT_IBE_ENABLE | PORT_SLEW_RATE_MAX | PORT_PULL_NONE  | PORT_OUTPUT )}, /* PCR	114	: PORT_PIN_MODE_ETH */
	{PORT_INVALID_REG, STD_OFF, STD_OFF, 0u} /* end marker */
};
/*lint -restore */


static const ArcPort_OutConfigType PortOutConfigData[] = {
	{0u, PORT_GPDO_RESET}, /* GPDO	0 */
	{98u, PORT_GPDO_HIGH}, /* GPDO	98 */
	{99u, PORT_GPDO_RESET}, /* GPDO	99 */
	{PORT_INVALID_REG, 0u} /* end marker */
};



const Port_ConfigType PortConfigData =
{
  .padConfig = PortPadConfigData,
  .outConfig = PortOutConfigData,
  .inputSelectConfig = PortInputSelectConfigData
};


