/**
 * RTE Types Workarounds Header File
 *
 * This file is used to fix some problems when using the RTE together
 * with files produced elsewhere. Each workaround has its own documentation.
 */

#ifndef RTE_TYPE_WORKAROUNDS_H_
#define RTE_TYPE_WORKAROUNDS_H_

/**
 * SWCs generated by Simulink have internal typedefs for types that are only used within the SWC.
 * If another SWC (also generated by Simulink) uses the same type, but on a port, this type will be
 * part of the AUTOSAR model and hence be generated in Rte_Type.h. To protect against double declaration
 * each typedef in the Simulink files is guarded like this:
 *
 * #ifndef _DEFINED_TYPEDEF_FOR_T_U_mV_1_1_s16_
 * #define _DEFINED_TYPEDEF_FOR_T_U_mV_1_1_s16_
 * typedef int16_T T_U_mV_1_1_s16;
 * #endif
 *
 * By defining these macros we can make it easier to integrate Simulink SWCs with the ArcCore RTE.
 * Note that this is not AUTOSAR standard.
 */
#define _DEFINED_TYPEDEF_FOR_AnalogValue_

#define _DEFINED_TYPEDEF_FOR_ComM_InhibitionStatusType_

#define _DEFINED_TYPEDEF_FOR_ComM_ModeType_

#define _DEFINED_TYPEDEF_FOR_ComM_UserHandleType_

#define _DEFINED_TYPEDEF_FOR_ConstVoidPtr_

#define _DEFINED_TYPEDEF_FOR_CounterType_

#define _DEFINED_TYPEDEF_FOR_Dcm_ConfirmationStatusType_

#define _DEFINED_TYPEDEF_FOR_Dcm_NegativeResponseCodeType_

#define _DEFINED_TYPEDEF_FOR_Dcm_OpStatusType_

#define _DEFINED_TYPEDEF_FOR_Dcm_ProtocolType_

#define _DEFINED_TYPEDEF_FOR_Dcm_RoeStateType_

#define _DEFINED_TYPEDEF_FOR_Dcm_SecLevelType_

#define _DEFINED_TYPEDEF_FOR_Dcm_SesCtrlType_

#define _DEFINED_TYPEDEF_FOR_Dem_DTCFormatType_

#define _DEFINED_TYPEDEF_FOR_Dem_DTCOriginType_

#define _DEFINED_TYPEDEF_FOR_Dem_DTCStatusMaskType_

#define _DEFINED_TYPEDEF_FOR_Dem_EventIdType_

#define _DEFINED_TYPEDEF_FOR_Dem_EventStatusExtendedType_

#define _DEFINED_TYPEDEF_FOR_Dem_EventStatusType_

#define _DEFINED_TYPEDEF_FOR_Dem_IndicatorStatusType_

#define _DEFINED_TYPEDEF_FOR_Dem_InitMonitorReasonType_

#define _DEFINED_TYPEDEF_FOR_Dem_OperationCycleIdType_

#define _DEFINED_TYPEDEF_FOR_Dem_OperationCycleStateType_

#define _DEFINED_TYPEDEF_FOR_Dem_ReturnClearDTCType_

#define _DEFINED_TYPEDEF_FOR_DigitalLevel_

#define _DEFINED_TYPEDEF_FOR_Dlt_ApplicationIDType_

#define _DEFINED_TYPEDEF_FOR_Dlt_ContextIDType_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageArgumentCount_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageIDType_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageLogInfoType_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageLogLevelType_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageOptionsType_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageTraceInfoType_

#define _DEFINED_TYPEDEF_FOR_Dlt_MessageTraceType_

#define _DEFINED_TYPEDEF_FOR_Dlt_ReturnType_

#define _DEFINED_TYPEDEF_FOR_Dlt_SessionIDType_

#define _DEFINED_TYPEDEF_FOR_DutyCycle_

#define _DEFINED_TYPEDEF_FOR_EcuM_BootTargetType_

#define _DEFINED_TYPEDEF_FOR_EcuM_StateType_

#define _DEFINED_TYPEDEF_FOR_EcuM_UserType_

#define _DEFINED_TYPEDEF_FOR_Frequency_

#define _DEFINED_TYPEDEF_FOR_HTMSS_TestGroupType_

#define _DEFINED_TYPEDEF_FOR_HTMSS_TestResultType_

#define _DEFINED_TYPEDEF_FOR_IoHwAb_SignalType__

#define _DEFINED_TYPEDEF_FOR_NvM_BlockIdType_

#define _DEFINED_TYPEDEF_FOR_NvM_RequestResultType_

#define _DEFINED_TYPEDEF_FOR_Rtm_BswErrorType_

#define _DEFINED_TYPEDEF_FOR_Rtm_DetErrorType_

#define _DEFINED_TYPEDEF_FOR_Rtm_EntryType_

#define _DEFINED_TYPEDEF_FOR_Rtm_ErrorType_

#define _DEFINED_TYPEDEF_FOR_Rtm_ErrorUnionType_

#define _DEFINED_TYPEDEF_FOR_Rtm_HookErrorType_

#define _DEFINED_TYPEDEF_FOR_Rtm_SmalErrorType_

#define _DEFINED_TYPEDEF_FOR_Rtm_StatusType_

#define _DEFINED_TYPEDEF_FOR_SignalQuality_

#define _DEFINED_TYPEDEF_FOR_StbM_SynchronizedTimeBaseType_

#define _DEFINED_TYPEDEF_FOR_StbM_TimeBaseStatusType_

#define _DEFINED_TYPEDEF_FOR_StbM_TimeStampExtendedType_

#define _DEFINED_TYPEDEF_FOR_StbM_TimeStampType_

#define _DEFINED_TYPEDEF_FOR_StbM_UserDataType_

#define _DEFINED_TYPEDEF_FOR_TickRefType_

#define _DEFINED_TYPEDEF_FOR_TickType_

#define _DEFINED_TYPEDEF_FOR_VoidPtr_

#define _DEFINED_TYPEDEF_FOR_WdgM_CheckpointIdType_

#define _DEFINED_TYPEDEF_FOR_WdgM_GlobalStatusType_

#define _DEFINED_TYPEDEF_FOR_WdgM_LocalStatusType_

#define _DEFINED_TYPEDEF_FOR_WdgM_ModeType_

#define _DEFINED_TYPEDEF_FOR_WdgM_SupervisedEntityIdType_

#define _DEFINED_TYPEDEF_FOR_constUint16Ptr_

#define _DEFINED_TYPEDEF_FOR_constUint32Ptr_

#define _DEFINED_TYPEDEF_FOR_constUint8Ptr_

#define _DEFINED_TYPEDEF_FOR_uint16Ptr_

#define _DEFINED_TYPEDEF_FOR_uint32Ptr_

#define _DEFINED_TYPEDEF_FOR_uint8Ptr_

#endif /* RTE_TYPE_WORKAROUNDS_H_ */
